Date =
ADDCOLUMNS (
    CALENDAR (
        CALCULATE( MIN( Sales[OrderDate] ), ALL( Sales ) ),
        CALCULATE( MAX( Sales[OrderDate] ), ALL( Sales ) )
    ),
    "Year", YEAR([Date]),
    "Month Number", MONTH([Date]),
    "Month", FORMAT([Date], "MMMM"),
    "Month Short", FORMAT([Date], "MMM"),
    "Year-Month", FORMAT([Date], "YYYY-MM"),
    "Quarter", "Q" & FORMAT([Date], "Q"),
    "Weekday", FORMAT([Date], "dddd"),
    "Weekday Short", FORMAT([Date], "ddd")
)


